spring:
  application:
    name: big-data
  profiles:
    active: ${apollo_profile}
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=utf-8
    username: root
    passord: 123456
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8083

mybatis:
  type-aliases-package: com.jimmy.entity
  mapper-locations: classpath:mybatis/mapper/*.xml



