spring:
  application:
    name: treasure
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf-8
    username: root
    passord: 123456
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8081

mybatis:
  type-aliases-package: com.jimmy.entity
  mapper-locations: classpath:mybatis/mapper/*.xml



